name: The Judy Show
favicon: null
layout_spectrum: 0.5778712085448205
typography_spectrum: 0.07037707068957388
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9938216982409358
  lightness: 0.5973855038173497
  saturation: 0.06350861280225217
  rhythmicContrast: 0.19701582682318985
purpose: []
