name: The Judy Show
favicon: null
layout_spectrum: 0.5778712085448205
typography_spectrum: 0.07037707068957388
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ff0001'
    - '#888888'
    - '#feb16f'
  brandStrength: 0.5
  lightness: 0.5973855038173497
  saturation: 0.06350861280225217
  rhythmicContrast: 0.19701582682318985
purpose: []
